export const heroMovies = [
  {
    id: 1,
    title: "THẾ GIỚI KHỦNG LONG",
    englishTitle: "Jurassic World Rebirth",
    backgroundImage: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-TvxQWzxaNSoeLXas3vwOSjtvqU9lpN.png",
    logo: "/placeholder.svg?height=80&width=80",
    imdbRating: 6.2,
    quality: "4K",
    duration: "1h 16m",
    year: "2025",
    genres: ["Chiếu Rạp", "Gay Cấn", "Khoa Học", "Bí Ẩn", "Phiêu Lưu", "Giả Tưởng"],
    description:
      "Phim lấy bối cảnh 5 năm sau phần phim Thế Giới Khủng Long: Lãnh Địa (Jurassic World: Dominion). Thế Giới Khủng Long: Tái Sinh mở ra một chương mới đầy tính hành động, chúng kiến một đội khai thác thác dưa đến nơi nguy hiểm nhất trên Đất.",
  },
  {
    id: 2,
    title: "SPIDER-MAN: NO WAY HOME",
    englishTitle: "Spider-Man: No Way Home",
    backgroundImage: "/placeholder.svg?height=600&width=1200",
    logo: "/placeholder.svg?height=80&width=80",
    imdbRating: 8.4,
    quality: "4K",
    duration: "2h 28m",
    year: "2021",
    genres: ["Hành Động", "Phiêu Lưu", "Khoa Học Viễn Tưởng"],
    description:
      "Với danh tính Spider-Man giờ đã được tiết lộ, Peter nhờ Doctor Strange giúp đỡ. Khi một câu thần chú bị sai, những kẻ thù nguy hiểm từ các thế giới khác bắt đầu xu��t hiện, buộc Peter phải khám phá ra ý nghĩa thực sự của việc trở thành Spider-Man.",
  },
  {
    id: 3,
    title: "AVENGERS: ENDGAME",
    englishTitle: "Avengers: Endgame",
    backgroundImage: "/placeholder.svg?height=600&width=1200",
    logo: "/placeholder.svg?height=80&width=80",
    imdbRating: 8.4,
    quality: "4K",
    duration: "3h 1m",
    year: "2019",
    genres: ["Hành Động", "Phiêu Lưu", "Khoa Học Viễn Tưởng"],
    description:
      "Sau những sự kiện tàn khốc của Infinity War, vũ trụ đang trong tình trạng hỗn loạn. Với sự giúp đỡ của các đồng minh còn lại, các Avengers tập hợp một lần nữa để đảo ngược hành động của Thanos và khôi phục lại trật tự của vũ trụ.",
  },
]

export const relatedMovies = [
  { id: 1, image: "/placeholder.svg?height=120&width=80", title: "Fast X" },
  { id: 2, image: "/placeholder.svg?height=120&width=80", title: "Dune 2" },
  { id: 3, image: "/placeholder.svg?height=120&width=80", title: "The Flash" },
  { id: 4, image: "/placeholder.svg?height=120&width=80", title: "John Wick 4" },
  { id: 5, image: "/placeholder.svg?height=120&width=80", title: "Indiana Jones" },
  { id: 6, image: "/placeholder.svg?height=120&width=80", title: "Guardians 3" },
]




export const movies = [
  {
    id: 1,
    title: "Avengers: Endgame",
    year: "2024",
    rating: 8.9,
    duration: "181 phút",
    genre: "Hành Động, Khoa Học Viễn Tưởng",
    quality: "4K",
    subtitle: "Vietsub",
    views: "2.5M",
    trending: true,
  },
  {
    id: 2,
    title: "Spider-Man: No Way Home",
    year: "2024",
    rating: 8.7,
    duration: "148 phút",
    genre: "Hành Động, Phiêu Lưu",
    quality: "4K",
    subtitle: "Vietsub",
    views: "3.1M",
    trending: true,
  },
  {
    id: 3,
    title: "The Batman",
    year: "2024",
    rating: 8.5,
    duration: "176 phút",
    genre: "Hành Động, Tội Phạm",
    quality: "HD",
    subtitle: "Vietsub",
    views: "1.8M",
    trending: false,
  },
  {
    id: 4,
    title: "Top Gun: Maverick",
    year: "2024",
    rating: 8.8,
    duration: "130 phút",
    genre: "Hành Động, Drama",
    quality: "4K",
    subtitle: "Vietsub",
    views: "2.2M",
    trending: true,
  },
  {
    id: 5,
    title: "Black Panther",
    year: "2024",
    rating: 8.6,
    duration: "161 phút",
    genre: "Hành Động, Khoa Học Viễn Tưởng",
    quality: "HD",
    subtitle: "Vietsub",
    views: "1.9M",
    trending: false,
  },
  {
    id: 6,
    title: "Dune",
    year: "2024",
    rating: 8.4,
    duration: "155 phút",
    genre: "Khoa Học Viễn Tưởng, Drama",
    quality: "4K",
    subtitle: "Vietsub",
    views: "1.6M",
    trending: false,
  },
]